import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import "@fontsource/montserrat/400.css";
import "@fontsource/montserrat/500.css";
import "@fontsource/montserrat/600.css";
import "@fontsource/montserrat/700.css";
import "@fontsource/mulish/400.css";
import "@fontsource/mulish/500.css";
import "@fontsource/mulish/600.css";
import "@fontsource/mulish/700.css";

import { ProjectSection } from "../components/ProjectSection";
import { projectList } from "../models/ProjectList";
import { HeaderCreative } from "../components/HeaderCreative";
import { navlinks } from "../models/NavLinks";
import { Sidebar } from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="px-2 lg:px-20 py-2 flex items-center justify-between bg-white fixed top-0 left-0 right-0 z-50">
        <Image src="/logo.jpeg" alt="Logo" width={160} height={90} />
        <div className="hidden lg:flex items-center gap-8 text-sm">
          {navlinks.map(link => {
            return (
              <Link href={link.link} key={link.id}>
                <div className="flex items-center gap-1 uppercase font-montserrat font-medium">
                  <span className="text-perfume-700">{link.id}.</span>
                  <span>{link.name}</span>
                </div>
              </Link>
            );
          })}
          <button className="block text-perfume-700 border border-perfume-700 bg-perfume-100 px-3 py-2 rounded-md text-sm font-medium font-montserrat tracking-wider uppercase">
            Resume
          </button>
        </div>
        <Sidebar />
      </header>
      <div className="min-h-screen flex items-center relative" id="home">
        <main className="px-2 lg:px-60">
          <div className="flex flex-col-reverse gap-6 lg:gap-2 lg:flex-row">
            <div className="flex flex-col lg:flex-[3] justify-center xl:items-start md:items-center gap-3 lg:gap-6">
              <div className="flex flex-col gap-2 lg:gap-3">
                <h1 className="text-lg text-perfume-500 font-medium tracking-wider">
                  Hi, my name is
                </h1>
                <div className="space-y-1">
                  <h1 className="text-4xl lg:text-6xl tracking-tight font-montserrat font-bold  text-slate-900">
                    Simranjeet Kaur.
                  </h1>
                  <h2 className="text-4xl tracking-tight lg:text-6xl font-montserrat font-bold text-slate-400">
                    I build things for the web.
                  </h2>
                </div>
              </div>
              <div className="space-y-6">
                <p className="text-md lg:text-md tracking-tight text-slate-500">
                  I’m a software engineer specializing in building (and
                  occasionally designing) exceptional digital experiences.
                  Currently, I’m focused on building accessible, human-centered
                  products at Upstatement.
                </p>
                <button className="block text-perfume-700 border border-perfume-700 bg-perfume-100 p-3 rounded-md text-sm font-medium font-montserrat tracking-wider uppercase">
                  Explore projects!
                </button>
              </div>
            </div>
            <div className="bg-perfume-100 lg:bg-transparent p-3 lg:p-0 flex items-center justify-center rounded-md lg:flex-[2]">
              <HeaderCreative />
            </div>
          </div>
        </main>
      </div>
      <div
        className="min-h-screen px-2 lg:px-72 space-y-6 py-10 bg-perfume-100"
        id="about">
        <h1 className="text-2xl uppercase font-bold font-montserrat tracking-wider text-perfume-900">
          About Me
        </h1>
        <div className="flex flex-col-reverse lg:flex-row gap-4">
          <div className="flex flex-col gap-3 flex-1">
            <p className="text-slate-600">
              Hello! My name is Brittany and I enjoy creating things that live
              on the internet. My interest in web development started back in
              2012 when I decided to try editing custom Tumblr themes — turns
              out hacking together a custom reblog button taught me a lot about
              HTML & CSS!
            </p>
            <p className="text-slate-600">
              Fast-forward to today, and I’ve had the privilege of working at{" "}
              <span className="text-perfume-700 font-medium cursor-pointer">
                an advertising agency, a start-up
              </span>
              , a huge corporation, and a student-led design studio. My main
              focus these days is building accessible, inclusive products and
              digital experiences at Upstatement for a variety of clients.
            </p>
            <p className="text-slate-600">
              I also recently launched a course that covers everything you need
              to build a web app with the Spotify API using Node & React.
            </p>
            <p className="text-slate-600">
              Here are a few technologies I’ve been working with recently:
            </p>
            <div className="grid grid-cols-2">
              <ul className="ml-4 list-disc text-slate-600">
                <li>JavaScript (ES6+)</li>
                <li>React</li>
                <li>Node.js</li>
              </ul>
              <ul className="ml-4 list-disc text-slate-600">
                <li>TypeScript</li>
                <li>Eleventy</li>
                <li>WordPress</li>
              </ul>
            </div>
          </div>
          <div className="w-full flex justify-start lg:justify-center items-center flex-1">
            <div className="w-full h-auto lg:w-80 lg:h-80 rounded-md overflow-hidden lg:shadow-2xl lg:shadow-perfume-500">
              <Image
                alt="profile"
                src="/profile_picture.jpeg"
                width={200}
                height={200}
                className="w-full h-full object-contain rounded-md"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="min-h-screen px-2 lg:px-60 space-y-6 py-10" id="projects">
        <h1 className="text-2xl uppercase font-bold font-montserrat tracking-wider text-gray-700">
          Some Things I’ve Built
        </h1>
        <div className="flex flex-col gap-24">
          {projectList.map((p, index) => (
            <ProjectSection
              key={p.id}
              position={p.position}
              title={p.title}
              subtitle={p.subtitle}
              image={p.image}
              chips={p.chips}
              buttons={p.buttons}
              index={index + 1}
            />
          ))}
        </div>
      </div>

      <div
        className="min-h-screen flex flex-col justify-center items-center px-2 lg:px-60 space-y-3 py-10 bg-perfume-900"
        id="contact">
        <h1 className="text-perfume-300 font-semibold tracking-wider">
          What’s Next?
        </h1>
        <div className="space-y-6 flex flex-col items-center">
          <div className="flex flex-col items-center text-center space-y-3">
            <h1 className="text-5xl lg:text-6xl tracking-tight font-montserrat font-bold  text-perfume-50">
              Get In Touch
            </h1>
            <p className="lg:w-1/2 text-lg text-perfume-300">
              Although I’m not currently looking for any new opportunities, my
              inbox is always open. Whether you have a question or just want to
              say hi, I’ll try my best to get back to you!
            </p>
          </div>
          <button className="block text-perfume-100 border border-perfume-300 bg-perfume-700 p-3 rounded-md text-sm font-medium font-montserrat tracking-wider uppercase">
            say hello
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
